### ISSUE TITLE
examples don't compile

### ISSUE THREAD

**Issue by ConnyOnny** [oli-obk/camera_capture#1]
It's a dependency problem with piston:
````error: Could not compile `piston2d-gfx_graphics`.````
It's 72 times the same error:
````Use of undeclared type or module `gfx` ````

Exact command to reproduce:
````cargo run --release --example hello_camera````
My system is an Ubuntu x86_64 with `libv4l-dev` installed and a webcam which is known to work with other programs.

**Comment by oli-obk** [comment]
I'm really not sure how to keep up with these piston breaks. I'll add a nightly build to travis to ensure I get notified when it breaks. It works again
