### ISSUE TITLE
can you document your pkg-config

### ISSUE THREAD

**Issue by valarauca** [oli-obk/camera_capture#11]
On fedora26 the entry for `pkg-config` isn't automatically populated with package information. So some additional docs in how to link `libv4l2` would be helpful.

**Comment by oli-obk** [comment]
Uh.... I have no idea how to do that. Did you get it working? If so, what is needed for that?

**Comment by valarauca** [comment]
Sorry I ran into some... I guess distro complexity. `Fedora26` was populating `libv4l2.so.0` which wouldn't correctly link, but if I symlinked it to `libv4l2.so` it would function properly.
